### PR TITLE
Feature sum

### PR DESCRIPTION
**Pull request by ma-oliveiramarques**
Please, check my readline attempt.

### CODE REVIEW

**Review by pncsoares — DISMISSED** [review]
Sounds cool for the first attempt 🔥💪
What do you think that can be improved?

**Comment by ma-oliveiramarques** [comment]
> Sounds cool for the first attempt 🔥💪 What do you think that can be improved?

I'm not sure if something is missing in my code...

**Comment by pncsoares** [comment]
> > Sounds cool for the first attempt 🔥💪 What do you think that can be improved?
> 
> I'm not sure if something is missing in my code...

Nothing is missing and as I said, "Sounds cool for the first attempt 🔥💪" 👍 
I am just asking what do you think that can be improved because, the code is doing the following:

```
rl.question("Please, digit the first number to sum: ", function(num1) {
    rl.question("Please, digit the second number to sum: ", function (num2){
        console.log(`The result of your sum is: ${Number(num1) + Number(num2)}`);
        rl.close();
    });
});
```

But you had a function that does the sum for you:
```
function sum(num1, num2) {
    return num1 + num2;
}
```

Why didn't you used it instead of just adding the two numbers inline?

**Comment by ma-oliveiramarques** [comment]
> > > Sounds cool for the first attempt 🔥💪 What do you think that can be improved?
> 
> > 
> 
> > I'm not sure if something is missing in my code...
> 
> 
> 
> Nothing is missing and as I said, "Sounds cool for the first attempt 🔥💪" 👍 
> 
> I am just asking what do you think that can be improved because, the code is doing the following:
> 
> 
> 
> ```
> 
> rl.question("Please, digit the first number to sum: ", function(num1) {
> 
>     rl.question("Please, digit the second number to sum: ", function (num2){
> 
>         console.log(`The result of your sum is: ${Number(num1) + Number(num2)}`);
> 
>         rl.close();
> 
>     });
> 
> });
> 
> ```
> 
> 
> 
> But you had a function that does the sum for you:
> 
> ```
> 
> function sum(num1, num2) {
> 
>     return num1 + num2;
> 
> }
> 
> ```
> 
> 
> 
> Why didn't you used it instead of just adding the two numbers inline?

I couldn't find how to do it while I was reading the documentation. I tried to run my function as I did it before, but didn't work with the rl.question...

**Comment by pncsoares** [comment]
> 

No problem :) we'll discuss this in today's meeting

**Comment by pncsoares** [comment]
@ma-oliveiramarques due to technical issues we do not achieve to accomplish the main goal of this thread: discuss how we can improve the code, so, to exemplify, I've created the following algorithm:

```
import rl from 'readline';

var readline = rl.createInterface(
    process.stdin,
    process.stdout
);

let firstNumber = 0;
let secondNumber = 0;
let result = 0;

function sum() {
    result = firstNumber + secondNumber;
}

function showResult() {
    console.log(`The sum of ${firstNumber} with ${secondNumber} is: ${result}`);
}

function main() {
    readline.question('Enter first number: ', (num) => {
        firstNumber = parseFloat(num);

        readline.question('Enter second number: ', (num) => {
            secondNumber = parseFloat(num);

            sum();
            showResult();

            readline.close();
        });
    });
}

main();
```

And if you don't want to use functions at the moment:

```
import rl from 'readline';

var readline = rl.createInterface(
    process.stdin,
    process.stdout
);

function main() {
    readline.question('Enter first number: ', (num) => {
        const firstNumber = parseFloat(num);

        readline.question('Enter second number: ', (num) => {
            const secondNumber = parseFloat(num);

            const result = firstNumber + secondNumber
            console.log(`The sum of ${firstNumber} with ${secondNumber} is: ${result}`);

            readline.close();
        });
    });
}

main();
```

I think that is straight-forward but let me know if I can help with something else 😉

**Review by pncsoares — APPROVED** [review]

**Pull request merged**
